# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "keizoku"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rory McKinley"]
  s.date = "2012-07-30"
  s.description = "Simple CI using Git"
  s.email = "rorymckinley@gmail.com"
  s.executables = ["keizoku-cronjob", "keizoku-init", "keizoku-integrate", "keizoku-post-receive-hook", "keizoku-validate-rake-spec"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/keizoku-cronjob",
    "bin/keizoku-init",
    "bin/keizoku-integrate",
    "bin/keizoku-post-receive-hook",
    "bin/keizoku-validate-rake-spec",
    "examples/keizoku-post-receive-hook.conf",
    "keizoku.gemspec",
    "lib/keizoku.rb",
    "lib/keizoku/git_hook.rb",
    "lib/keizoku/git_repo.rb",
    "lib/keizoku/integration.rb",
    "lib/keizoku/integration_dispatcher.rb",
    "lib/keizoku/integration_queuer.rb",
    "lib/keizoku/integration_scheduler.rb",
    "spec/keizoku/git_hook_spec.rb",
    "spec/keizoku/git_repo_spec.rb",
    "spec/keizoku/integration_dispatcher_spec.rb",
    "spec/keizoku/integration_queuer_spec.rb",
    "spec/keizoku/integration_scheduler_spec.rb",
    "spec/keizoku/integration_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/fake-keizoku-integration",
    "spec/support/fake_integration.rb",
    "spec/support/fake_io.rb"
  ]
  s.homepage = "http://github.com/rorymckinley/keizoku"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple CI using Git"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<lockfile>, ["~> 2.1.0"])
      s.add_runtime_dependency(%q<uuid>, ["~> 2.3.5"])
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.4"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<lockfile>, ["~> 2.1.0"])
      s.add_dependency(%q<uuid>, ["~> 2.3.5"])
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.4"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<lockfile>, ["~> 2.1.0"])
    s.add_dependency(%q<uuid>, ["~> 2.3.5"])
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.4"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

